---
dev_addr: "127.0.0.1:8001"
edit_uri: "edit/main/jdiff/docs"
site_dir: "jdiff/static/jdiff/docs"
site_name: "Jdiff Documentation"
site_url: "https://jdiff.readthedocs.io/"
repo_url: "https://github.com/networktocode-llc/jdiff"
copyright: "Copyright &copy; The Authors"
theme:
  name: "material"
  navigation_depth: 4
  custom_dir: "docs/assets/overrides"
  hljs_languages:
    - "python"
    - "yaml"
  features:
    - "content.code.annotate"
    - "content.code.copy"
    - "content.tabs.link"
    - "navigation.footer"
    - "navigation.tabs"
    - "navigation.tabs.sticky"
    - "navigation.tracking"
    - "search.highlight"
    - "search.share"
    - "search.suggest"
  favicon: "assets/favicon.ico"
  logo: "assets/networktocode_logo.svg"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      primary: "black"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to dark mode"

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      primary: "black"
      toggle:
        icon: "material/weather-night"
        name: "Switch to light mode"

validation:
  absolute_links: "warn"
  anchors: "warn"
  omitted_files: "warn"
  unrecognized_links: "warn"

extra_css:
  - "assets/extra.css"

extra:
  generator: false
  ntc_sponsor: true
  social:
    - icon: "fontawesome/solid/rss"
      link: "https://blog.networktocode.com/"
      name: "Network to Code Blog"
    - icon: "fontawesome/brands/youtube"
      link: "https://www.youtube.com/channel/UCwBh-dDdoqzxXKyvTw3BuTw"
      name: "Network to Code Videos"
    - icon: "fontawesome/brands/slack"
      link: "https://www.networktocode.com/community/"
      name: "Network to Code Community"
    - icon: "fontawesome/brands/github"
      link: "https://github.com/networktocode/"
      name: "GitHub Organization"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/networktocode"
      name: "Network to Code Twitter"
markdown_extensions:
  - "markdown_version_annotations":
      admonition_tag: "???"
  - "admonition"
  - "toc":
      permalink: true
  - "attr_list"
  - "markdown_data_tables":
      base_path: "docs"
  - "md_in_html"
  - "pymdownx.details"
  # Need pymdownx.emoji for Grid icon search
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - "pymdownx.highlight":
      anchor_linenums: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences":
      custom_fences:
        - name: "mermaid"
          class: "mermaid"
          format: !!python/name:pymdownx.superfences.fence_code_format
  - "pymdownx.tabbed":
      "alternate_style": true
  - "pymdownx.tilde"

plugins:
  - "search"
  - "gen-files":
      scripts:
        - "docs/generate_code_reference_pages.py"
  - "glightbox":
      manual: true # See https://blueswen.github.io/mkdocs-glightbox/flexibility/enable-by-image-or-page/
  - "section-index"
  - "mkdocstrings":
      default_handler: "python"
      handlers:
        python:
          paths: ["."]
          options:
            heading_level: 1
            show_root_heading: true
            show_root_members_full_path: true
            show_source: false

nav:
  - Overview: "index.md"
  - User Guide:
      - Library Overview: "user/lib_overview.md"
      - Getting Started: "user/lib_getting_started.md"
      - Architecture Overview: "user/architecture.md"
      - Usage: "user/usage.md"
      - Frequently Asked Questions: "user/faq.md"
  - Administrator Guide:
      - Install and Configure: "admin/install.md"
      - Upgrade: "admin/upgrade.md"
      - Uninstall: "admin/uninstall.md"
      - Release Notes:
          - "admin/release_notes/index.md"
          - v0.0: "admin/release_notes/version_0.0.md"
          - v1.0: "admin/release_notes/version_1.0.md"
  - Developer Guide:
      - Extending the Library: "dev/extending.md"
      - Contributing to the Library: "dev/contributing.md"
      - Development Environment: "dev/dev_environment.md"
      - Architecture Decisions: "dev/arch_decision.md"
      - Code Reference:
        - Jdiff: "code-reference/jdiff/__init__.md"
        - check_types: "code-reference/jdiff/check_types.md"
        - evaluators: "code-reference/jdiff/evaluators.md"
        - extract_data: "code-reference/jdiff/extract_data.md"
        - operator: "code-reference/jdiff/operator.md"
        - jdiff_utils: "code-reference/jdiff/utils/__init__.md"
        - data_normalization: "code-reference/jdiff/utils/data_normalization.md"
        - diff_helpers: "code-reference/jdiff/utils/diff_helpers.md"
        - jmespath_parsers: "code-reference/jdiff/utils/jmespath_parsers.md"
