---
dev_addr: "127.0.0.1:8001"
edit_uri: "edit/docs"
site_name: "jdiff Documentation"
site_url: "https://jdiff.readthedocs.io/"
site_dir: "jdiff/docs"
repo_url: "https://github.com/networktocode-llc/jdiff"
python:
  install:
    - requirements: "docs/requirements.txt"
theme:
  name: "readthedocs"
  navigation_depth: 4
  hljs_languages:
    - "django"
    - "yaml"
extra_css:
  - "extra.css"
markdown_extensions:
  - "admonition"
  - toc:
      permalink: true
nav:
  - Introduction: "index.md"
  - Usage: "usage.md"
  - Architecture: "architecture.md"
# Future docs
# - Examples: "example.md"
# - Development Environment: "development.md"
