# Generated by Django 3.2.18 on 2023-03-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmonitor',
            name='lrtm',
            field=models.BooleanField(blank=True, default='default', null=True),
        ),
    ]
