# Generated by Django 3.2.18 on 2023-03-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lb_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='healthmonitor',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='servicegroup',
            name='tags',
        ),
    ]
