# Generated by Django 3.2.18 on 2023-05-01 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lb_models', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthMonitor',
            new_name='Monitor',
        ),
    ]
