# Generated by Django 3.2.17 on 2023-02-13 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0008_prefix_vlan_vlangroup_location'),
        ('lb_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='ipv4_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ipam.ipaddress'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='ipv6_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ipam.ipaddress'),
        ),
        migrations.AlterField(
            model_name='vippoolmember',
            name='ipv4_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ipam.ipaddress'),
        ),
        migrations.AlterField(
            model_name='vippoolmember',
            name='ipv6_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ipam.ipaddress'),
        ),
    ]
