# Generated by Django 3.2.16 on 2023-02-01 09:44

from django.db import migrations, models
import nautobot.core.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lb_models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VIPPoolResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "slug",
                    nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from="name", unique=True),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=100)),
                ("code", models.SmallIntegerField()),
                ("string", models.CharField(max_length=200)),
                ("send", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
