# Generated by Django 3.2.17 on 2023-02-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='fqdn',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vippoolmember',
            name='fqdn',
            field=models.CharField(max_length=200),
        ),
    ]
