# Generated by Django 3.2.18 on 2023-02-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lb_models", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vipcertificate",
            name="version_number",
            field=models.CharField(max_length=50),
        ),
    ]
