# Generated by Django 3.2.18 on 2023-06-07 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lb_models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vserver",
            name="td",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32767),
                ],
            ),
        ),
    ]
