# Generated by Django 3.2.18 on 2023-03-22 09:31

from django.db import migrations
import nautobot.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lb_models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='signature_algorithm',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='signature_algorithm_id',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='subject_pub_key',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='subject_pub_key_algorithm',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='slug',
            field=nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from='name', unique=True),
        ),
    ]
