# Generated by Django 3.2.17 on 2023-02-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='vip_args',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
