# Generated by Django 3.2.17 on 2023-02-15 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb_models', '0002_alter_vip_vip_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vippoolmember',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1)]),
        ),
    ]
