# Generated by Django 3.2.18 on 2023-03-20 14:40

from django.db import migrations, models
import nautobot.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lb_models', '0002_alter_healthmonitor_lrtm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='slug',
            field=nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from='certificate', unique=True),
        ),
        migrations.AlterField(
            model_name='healthmonitor',
            name='lrtm',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
