# Generated by Django 3.2.18 on 2023-05-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb_models', '0002_rename_healthmonitor_monitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='description',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='code',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='httprequest',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='receive',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='secure',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='send',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='string',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='url',
        ),
        migrations.AddField(
            model_name='monitor',
            name='args',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='snow_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='lrtm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
