# Generated by Django 3.2.19 on 2023-06-08 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lb_models", "0002_vserver_td"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicegroupmemberbinding",
            name="server_port",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(65535),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
