# Generated by Django 3.2.17 on 2023-02-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb_models', '0002_auto_20230214_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vippoolmember',
            name='member_args',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
