# Generated by Django 3.2.17 on 2023-02-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lb_models", "0002_auto_20230213_1440"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viphealthmonitor",
            name="url",
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
