# Generated by Django 3.2.19 on 2023-06-08 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lb_models", "0003_alter_servicegroupmemberbinding_server_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="snow_id",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="td",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32767),
                ],
            ),
        ),
    ]
