# Generated by Django 3.2.16 on 2023-02-01 13:13

from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lb_models", "0003_viphealthmonitor_vippoolmember"),
    ]

    operations = [
        migrations.CreateModel(
            name="VIPPool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "slug",
                    nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from="name", unique=True),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=50)),
                (
                    "member",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="lb_models.vippoolmember"),
                ),
                (
                    "monitor",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="lb_models.viphealthmonitor"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
