# Generated by Django 3.2.19 on 2023-06-12 09:11

from django.db import migrations
import nautobot.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("lb_models", "0004_auto_20230608_0926"),
    ]

    operations = [
        migrations.RenameField(
            model_name="monitor",
            old_name="args",
            new_name="monitor_args",
        ),
        migrations.RenameField(
            model_name="monitor",
            old_name="name",
            new_name="monitor_name",
        ),
        migrations.RenameField(
            model_name="monitor",
            old_name="type",
            new_name="monitor_type",
        ),
        migrations.RenameField(
            model_name="monitor",
            old_name="snow_id",
            new_name="snow_ticket_id",
        ),
        migrations.RenameField(
            model_name="server",
            old_name="name",
            new_name="server_name",
        ),
        migrations.RenameField(
            model_name="server",
            old_name="td",
            new_name="server_td",
        ),
        migrations.RenameField(
            model_name="server",
            old_name="snow_id",
            new_name="snow_ticket_id",
        ),
        migrations.RenameField(
            model_name="serverservicegroupbinding",
            old_name="name",
            new_name="group_server_name",
        ),
        migrations.RenameField(
            model_name="servicegroup",
            old_name="name",
            new_name="service_group_name",
        ),
        migrations.RenameField(
            model_name="servicegroup",
            old_name="snow_id",
            new_name="snow_ticket_id",
        ),
        migrations.RenameField(
            model_name="servicegroupmemberbinding",
            old_name="name",
            new_name="group_binding_name",
        ),
        migrations.RenameField(
            model_name="servicegroupmonitorbinding",
            old_name="name",
            new_name="group_monitor_name",
        ),
        migrations.RenameField(
            model_name="sslcertkey",
            old_name="name",
            new_name="key_name",
        ),
        migrations.RenameField(
            model_name="sslcertkey",
            old_name="password",
            new_name="key_password",
        ),
        migrations.RenameField(
            model_name="sslcertkey",
            old_name="snow_id",
            new_name="snow_ticket_id",
        ),
        migrations.RenameField(
            model_name="sslserverbinding",
            old_name="name",
            new_name="server_name",
        ),
        migrations.RenameField(
            model_name="vserver",
            old_name="snow_id",
            new_name="snow_ticket_id",
        ),
        migrations.RenameField(
            model_name="vserver",
            old_name="args",
            new_name="vserver_args",
        ),
        migrations.RenameField(
            model_name="vserver",
            old_name="name",
            new_name="vserver_name",
        ),
        migrations.RenameField(
            model_name="vserver",
            old_name="td",
            new_name="vserver_td",
        ),
        migrations.AlterField(
            model_name="monitor",
            name="slug",
            field=nautobot.core.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="monitor_name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="slug",
            field=nautobot.core.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="server_name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="servicegroup",
            name="slug",
            field=nautobot.core.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="service_group_name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="servicegroupmemberbinding",
            name="slug",
            field=nautobot.core.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="group_binding_name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="servicegroupmonitorbinding",
            name="slug",
            field=nautobot.core.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="group_monitor_name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="sslcertkey",
            name="slug",
            field=nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from="key_name", unique=True),
        ),
        migrations.AlterField(
            model_name="sslserverbinding",
            name="slug",
            field=nautobot.core.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="server_name", unique=True
            ),
        ),
    ]
