# Generated by Django 3.2.16 on 2023-02-06 08:51

from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0019_device_redundancy_group_data_migration"),
        ("ipam", "0009_alter_vlan_name"),
        ("lb_models", "0004_vippool"),
    ]

    operations = [
        migrations.CreateModel(
            name="VIP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "slug",
                    nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from="name", unique=True),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=50)),
                ("fqdn", models.URLField()),
                ("protocol", models.CharField(max_length=20)),
                ("port", models.SmallIntegerField(blank=True, null=True)),
                ("method", models.CharField(max_length=50)),
                ("owner", models.CharField(max_length=50)),
                ("vip_args", models.JSONField()),
                (
                    "certificate",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lb_models.vipcertificate"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="dcim.device",
                    ),
                ),
                (
                    "interface",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="dcim.interface",
                    ),
                ),
                (
                    "ipv4_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ipam.ipaddress",
                    ),
                ),
                (
                    "ipv6_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ipam.ipaddress",
                    ),
                ),
                ("pool", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="lb_models.vippool")),
                (
                    "vlan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ipam.vlan",
                    ),
                ),
                (
                    "vrf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ipam.vrf",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="VIPPoolResponse",
        ),
        migrations.AddField(
            model_name="viphealthmonitor",
            name="code",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="viphealthmonitor",
            name="string",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="viphealthmonitor",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="viphealthmonitor",
            name="receive",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="viphealthmonitor",
            name="send",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="viphealthmonitor",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="viphealthmonitor",
            name="url",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="vippoolmember",
            name="fqdn",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="vippoolmember",
            name="port",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
